environment:
  VisualStudioVersion: 11.0

# TODO: add x64, fix issue: LNK1158: cannot run 'cvtres.exe'
platform:
  - Win32

# TODO: add VSDebug
configuration:
  - Release

install:
  - cmd: git clone https://github.com/libyal/libyal.git && move libyal ..\
  - cmd: git clone https://github.com/joachimmetz/dokan.git && move dokan ..\
  - ps: .\syncwinflexbison.ps1

before_build:
  - ps: .\synclibs.ps1
  - ps: .\autogen.ps1
  - cmd: ..\win_flex_bison\win_flex.exe -Cf libfplist\libfplist_xml_scanner.l && move lex.yy.c libfplist\libfplist_xml_scanner.c
  - cmd: ..\win_flex_bison\win_bison.exe -d -v -l -p xml_scanner_ libfplist\libfplist_xml_parser.y && move libfplist_xml_parser.tab.c libfplist\libfplist_xml_parser.c && move libfplist_xml_parser.tab.h libfplist\libfplist_xml_parser.h
  - cmd: C:\Python27\python.exe ..\libyal\scripts\msvscpp-convert.py --to 2010 msvscpp\libmodi.sln

build:
  project: vs2010\libmodi.sln

test_script:
  - ps: .\runtests.ps1

